#!/usr/bin/perl -w

use strict;
use Getopt::Std qw/getopts/;


use vars qw/%opts/;

%opts = ();



###### usage_text()
#
#   Returns a usage text (does not print it). Tries not to exceed an 80 column screen.
#

sub usage_text() {
    return join("\n",
        "Usage: $0 [-s <setname>] [length]",
        "",
        "Returns a random string made up from a given set of characters,",
        "suitable for use as a password, with a length of 'length' chars,",
        "or 10, if no length is given.",
        "",
        "    -s: use a named set of characters instead of the default set. ",
        "       Names are: safe, anum, num, alpha, lalpha, ualpha",
        "",
        "It is not defined, which characters the default charset consists of,",
        "i.e. this may change in a future version.",
        "",
        "pwgen.pl (C) Copyright 2003-2009 by Calocybe Creations",
        ""
    );
}




######  main()
#
#

sub main() {
    my @charset;


# TODO: provide -h or -? option
    getopts('s:', \%opts);
    print(usage_text()), return 1 unless (@ARGV <= 1);


    # default charset
    @charset = ('0'..'9', 'A'..'Z', '!', '$', '&', '/', ',', '.', '0'..'9', 'a'..'z', '(', ')', '=', '-', '+');

    if ($opts{'s'}) {
        $opts{'s'} = lc($opts{'s'});

        $opts{'s'} eq 'safe' and
            @charset = ('0'..'9', 'A'..'Z', 'a'..'z', ',', '.') or
        $opts{'s'} eq 'anum' and
            @charset = ('0'..'9', 'A'..'Z', 'a'..'z') or
        $opts{'s'} eq 'num' and
            @charset = ('0'..'9') or
        $opts{'s'} eq 'alpha' and
            @charset = ('A'..'Z', 'a'..'z') or
        $opts{'s'} eq 'lalpha' and
            @charset = ('a'..'z') or
        $opts{'s'} eq 'ualpha' and
            @charset = ('A'..'Z') or
        0;
    }


    my $length = $ARGV[0] || 10;

    print($charset[int(rand(scalar(@charset)))]) while($length--);
    print("\n");
}


exit(main());

